cargo-features = ["resolver"]

[package]
name = "near-dm-indexer"
version = "0.1.0"
authors = ["billettc <charles@cbillette.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "=0.11.0-beta.2"
clap = "3.0.0-beta.1"
openssl-probe = "0.1.2"
serde_json = "1.0.55"
tokio = { version = "1.1", features = ["sync"] }
tracing = "0.1.13"
tracing-subscriber = "0.2.4"

near-indexer = { git = "https://github.com/near/nearcore", rev="6cc390944660354fdd28e1f52071ea03a5d5634f" }
