cargo-features = ["resolver"]

[package]
name = "near-dm-indexer"
version = "0.1.0"
authors = ["billettc <charles@cbillette.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "=0.11.0-beta.2"
base64 = "0.11"
clap = "3.0.0-beta.1"
hex = "0.4"
openssl-probe = "0.1.2"
serde_json = "1.0.55"
tokio = { version = "1.1", features = ["sync"] }
tracing = "0.1.13"
tracing-subscriber = "0.2.4"

near-store = { git = "https://github.com/streamingfast/nearcore", rev="bd363ff82", features = ["protocol_feature_block_header_v3"] } # branch="feature/final_block_height_1_22_0"
near-chain = { git = "https://github.com/streamingfast/nearcore", rev="bd363ff82", features = ["protocol_feature_block_header_v3"] } # branch="feature/final_block_height_1_22_0"
near-primitives = { git = "https://github.com/streamingfast/nearcore", rev="bd363ff82", features = ["protocol_feature_block_header_v3"]}
near-indexer = { git = "https://github.com/streamingfast/nearcore", rev="bd363ff82"} # branch="feature/final_block_height_1_22_0"
near-crypto = { git = "https://github.com/streamingfast/nearcore", rev="bd363ff82" } # branch="feature/final_block_height_1_22_0"
near-vm-errors = { git = "https://github.com/streamingfast/nearcore", rev="bd363ff82" } # branch="feature/final_block_height_1_22_0"
near-epoch-manager = { git = "https://github.com/streamingfast/nearcore", rev="bd363ff82", features = ["protocol_feature_block_header_v3"] } # branch="feature/final_block_height_1_22_0"
near-client = { git = "https://github.com/streamingfast/nearcore", rev="bd363ff82", features = ["protocol_feature_block_header_v3"] } # branch="feature/final_block_height_1_22_0"
nearcore = { git = "https://github.com/streamingfast/nearcore", rev="bd363ff82", features = ["protocol_feature_block_header_v3"]} # branch="feature/final_block_height_1_22_0"

prost = "0.8"
prost-types = "0.8"
tonic = "0.5.0"

[build-dependencies]
tonic-build = "0.5.0"

[features]
default = ["nearcore/protocol_feature_block_header_v3", "near-primitives/protocol_feature_block_header_v3", "near-chain/protocol_feature_block_header_v3", "near-store/protocol_feature_block_header_v3", "near-epoch-manager/protocol_feature_block_header_v3", "near-client/protocol_feature_block_header_v3"]