[workspace]
members = ["deepmind-pb"]

[package]
name = "near-dm-indexer"
version = "1.25.0"
authors = ["StreamingFast Developers <dev@streamingfast.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-codec = "=0.4.0"
actix_derive = "^0.6.0"
actix-tls = "3.0.3"
actix-http = "3.0.4"
actix-server = "2.1.1"
actix-service = "2.0.1"
actix-web = "4.0.1"
actix-web-codegen = "4.0.0"
actix-utils = "=3.0.0"
base64 = "0.11"
clap = { version = "3.1.6", features = ["derive"] }
hex = "0.4"
openssl-probe = "0.1.4"
serde_json = "1.0.55"
tokio = { version = "1.1", features = ["sync"] }
tracing = "0.1.13"
tracing-subscriber = "0.2.4"
prost = "0.8"
prost-types = "0.8"
tonic = "0.5.0"

# Added to get rid of a dependencies error even if we do not use it
itertools = "0.10.3"

near-indexer = { git = "https://github.com/streamingfast/nearcore", rev="1.27.0-rc.1-dm" }
near-crypto = { git = "https://github.com/streamingfast/nearcore", rev="1.27.0-rc.1-dm" }
near-vm-errors = { git = "https://github.com/streamingfast/nearcore", rev="1.27.0-rc.1-dm" }

[build-dependencies]
tonic-build = "0.5.0"
