[workspace]
members = ["deepmind-pb"]

[package]
name = "near-dm-indexer"
version = "1.24.0-rc.3"
authors = ["StreamingFast Developers <dev@streamingfast.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "=0.11.0-beta.2"
actix-codec = "=0.4.0"
actix_derive = "=0.6.0-beta.1"
actix-tls = "=3.0.0-beta.6"
actix-http = "=3.0.0-beta.6"
actix-server = "=2.0.0-beta.6"
actix-service = "=2.0.1"
actix-web = "=4.0.0-beta.6"
actix-web-codegen = "=0.5.0-beta.2"
actix-utils = "=3.0.0"
base64 = "0.11"
clap = "=3.0.0-beta.2"
clap_derive = "=3.0.0-beta.2"
hex = "0.4"
openssl-probe = "0.1.4"
serde_json = "1.0.55"
tokio = { version = "1.1", features = ["sync"] }
tracing = "0.1.13"
tracing-subscriber = "0.2.4"
prost = "0.8"
prost-types = "0.8"
tonic = "0.5.0"

near-indexer = { git = "https://github.com/streamingfast/nearcore", rev="0d1369e999c67cd4cae9d448d536814ecd1f9f9d" }
near-crypto = { git = "https://github.com/streamingfast/nearcore", rev="0d1369e999c67cd4cae9d448d536814ecd1f9f9d" }
near-vm-errors = { git = "https://github.com/streamingfast/nearcore", rev="0d1369e999c67cd4cae9d448d536814ecd1f9f9d" }


[build-dependencies]
tonic-build = "0.5.0"
