cargo-features = ["resolver"]

[package]
name = "near-dm-indexer"
version = "0.1.0"
authors = ["billettc <charles@cbillette.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "=0.11.0-beta.2"
clap = "3.0.0-beta.1"
hex = "0.4"
openssl-probe = "0.1.2"
serde_json = "1.0.55"
tokio = { version = "1.1", features = ["sync"] }
tracing = "0.1.13"
tracing-subscriber = "0.2.4"

near-indexer = { git = "https://github.com/streamingfast/nearcore", branch="feature/final_block_height" } # base on 1.21.0
#near-indexer = { path = "/Users/cbillett/devel/sf/nearcore/chain/indexer" }
near-crypto = "0.1.0"

prost = "0.8"
prost-types = "0.8"
tonic = "0.5.0"

[build-dependencies]
tonic-build = "0.5.0"
